# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
    providers:
        user_provider:
            entity:
                class: AppBundle:User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            provider: user_provider
            json_login:
                check_path:       /api/login_check
                username_path: username
                password_path: password
                success_handler:  lexik_jwt_authentication.handler.authentication_success
                failure_handler:  lexik_jwt_authentication.handler.authentication_failure
        api_doc:
            pattern:  ^/api/doc
            stateless: true
            anonymous: true
        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
    access_control:
        - { path: ^/$,       role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/doc,       role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       role: IS_AUTHENTICATED_FULLY }